#!/usr/bin/env bash

code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension CraigMaslowski.erb
code --install-extension PKief.material-icon-theme
code --install-extension PeterJausovec.vscode-docker
code --install-extension Tyriar.sort-lines
code --install-extension alefragnani.project-manager
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension formulahendry.auto-rename-tag
code --install-extension ginfuru.ginfuru-vscode-jekyll-syntax
code --install-extension ginfuru.vscode-jekyll-snippets
code --install-extension hollowtree.vue-snippets
code --install-extension marcostazi.VS-code-vagrantfile
code --install-extension miguel-savignano.ruby-symbols
code --install-extension mrmlnc.vscode-apache
code --install-extension neilbrayfield.php-docblocker
code --install-extension neilding.language-liquid
code --install-extension octref.vetur
code --install-extension onecentlin.laravel-blade
code --install-extension patbenatar.advanced-new-file
code --install-extension pnp.polacode
code --install-extension rebornix.Ruby
code --install-extension robinbentley.sass-indented
code --install-extension shanoor.vscode-nginx
code --install-extension sianglim.slim
code --install-extension viatsko.theme-base16-ocean-dark
code --install-extension wayou.vscode-todo-highlight
code --install-extension whatwedo.twig
code --install-extension wmaurer.change-case
