#!/usr/bin/env bash

# Configuration files
find ~/dotfiles/vscode -name '*.json' | xargs -I file ln -fs file ~/Library/Application\ Support/VSCodium/User/

# Packages
vscodium --install-extension alefragnani.project-manager
vscodium --install-extension atipugin.rails-partial
vscodium --install-extension bmewburn.vscode-intelephense-client
vscodium --install-extension bradlc.vscode-tailwindcss
vscodium --install-extension BriteSnow.vscode-toggle-quotes
vscodium --install-extension bung87.rails
vscodium --install-extension bung87.vscode-gemfile
vscodium --install-extension bungcip.better-toml
vscodium --install-extension christian-kohler.npm-intellisense
vscodium --install-extension CoenraadS.bracket-pair-colorizer
vscodium --install-extension CraigMaslowski.erb
vscodium --install-extension cssho.vscode-svgviewer
vscodium --install-extension dbaeumer.vscode-eslint
vscodium --install-extension eamodio.gitlens
vscodium --install-extension formulahendry.auto-close-tag
vscodium --install-extension formulahendry.auto-rename-tag
vscodium --install-extension haaaad.ansible
vscodium --install-extension hollowtree.vue-snippets
vscodium --install-extension HookyQR.beautify
vscodium --install-extension Hridoy.rails-snippets
vscodium --install-extension karunamurti.haml
vscodium --install-extension marcostazi.VS-code-vagrantfile
vscodium --install-extension mechatroner.rainbow-csv
vscodium --install-extension miguel-savignano.ruby-symbols
vscodium --install-extension mikestead.dotenv
vscodium --install-extension mrmlnc.vscode-apache
vscodium --install-extension neilbrayfield.php-docblocker
vscodium --install-extension octref.vetur
vscodium --install-extension onecentlin.laravel-blade
vscodium --install-extension PeterJausovec.vscode-docker
vscodium --install-extension PKief.material-icon-theme
vscodium --install-extension pnp.polacode
vscodium --install-extension possan.nbsp-vscode
vscodium --install-extension rebornix.ruby
vscodium --install-extension redhat.vscode-yaml
vscodium --install-extension ritwickdey.LiveServer
vscodium --install-extension robinbentley.sass-indented
vscodium --install-extension sdras.night-owl
vscodium --install-extension shanehofstetter.rails-i18n
vscodium --install-extension shanoor.vscode-nginx
vscodium --install-extension sianglim.slim
vscodium --install-extension sporto.rails-go-to-spec
vscodium --install-extension steoates.autoimport
vscodium --install-extension sysoev.language-stylus
vscodium --install-extension TomasHubelbauer.vscode-markdown-table-format
vscodium --install-extension tomoki1207.pdf
vscodium --install-extension Tyriar.sort-lines
vscodium --install-extension usernamehw.indent-one-space
vscodium --install-extension vscoss.vscode-ansible
vscodium --install-extension wayou.vscode-todo-highlight
vscodium --install-extension whatwedo.twig
vscodium --install-extension wmaurer.change-case
vscodium --install-extension yzhang.markdown-all-in-one
vscodium --install-extension zhuangtongfa.Material-theme
vscodium --install-extension Zignd.html-css-class-completion
