#!/usr/bin/env bash

# Configuration files
find ~/dotfiles/vscode -name '*.json' | xargs -I file ln -fs file ~/Library/Application\ Support/VSCodium/User/

# Packages
codium --install-extension alefragnani.project-manager
codium --install-extension atipugin.rails-partial
codium --install-extension bmewburn.vscode-intelephense-client
codium --install-extension bradlc.vscode-tailwindcss
codium --install-extension BriteSnow.vscode-toggle-quotes
codium --install-extension bung87.rails
codium --install-extension bung87.vscode-gemfile
codium --install-extension bungcip.better-toml
codium --install-extension christian-kohler.npm-intellisense
codium --install-extension CoenraadS.bracket-pair-colorizer
codium --install-extension CraigMaslowski.erb
codium --install-extension cssho.vscode-svgviewer
codium --install-extension dbaeumer.vscode-eslint
codium --install-extension eamodio.gitlens
codium --install-extension formulahendry.auto-close-tag
codium --install-extension formulahendry.auto-rename-tag
codium --install-extension haaaad.ansible
codium --install-extension hollowtree.vue-snippets
codium --install-extension HookyQR.beautify
codium --install-extension Hridoy.rails-snippets
codium --install-extension karunamurti.haml
codium --install-extension marcostazi.VS-code-vagrantfile
codium --install-extension mechatroner.rainbow-csv
codium --install-extension miguel-savignano.ruby-symbols
codium --install-extension mikestead.dotenv
codium --install-extension mrmlnc.vscode-apache
codium --install-extension neilbrayfield.php-docblocker
codium --install-extension octref.vetur
codium --install-extension onecentlin.laravel-blade
codium --install-extension PeterJausovec.vscode-docker
codium --install-extension PKief.material-icon-theme
codium --install-extension pnp.polacode
codium --install-extension possan.nbsp-vscode
codium --install-extension rebornix.ruby
codium --install-extension redhat.vscode-yaml
codium --install-extension ritwickdey.LiveServer
codium --install-extension robinbentley.sass-indented
codium --install-extension sdras.night-owl
codium --install-extension shanehofstetter.rails-i18n
codium --install-extension shanoor.vscode-nginx
codium --install-extension sianglim.slim
codium --install-extension sporto.rails-go-to-spec
codium --install-extension steoates.autoimport
codium --install-extension sysoev.language-stylus
codium --install-extension TomasHubelbauer.vscode-markdown-table-format
codium --install-extension tomoki1207.pdf
codium --install-extension Tyriar.sort-lines
codium --install-extension usernamehw.indent-one-space
codium --install-extension vscoss.vscode-ansible
codium --install-extension wayou.vscode-todo-highlight
codium --install-extension whatwedo.twig
codium --install-extension wmaurer.change-case
codium --install-extension yzhang.markdown-all-in-one
codium --install-extension zhuangtongfa.Material-theme
codium --install-extension Zignd.html-css-class-completion
